name: Enforce Pull Before Push

on:
  push:
    branches:
      - main

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if branch is up-to-date
        run: |
          git fetch origin main
          LOCAL_HASH=$(git rev-parse HEAD)
          REMOTE_HASH=$(git rev-parse origin/main)

          if [ "$LOCAL_HASH" != "$REMOTE_HASH" ]; then
            echo "Your branch is not up to date! Please pull the latest changes before pushing."
            exit 1
          fi